# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grandkotlovanUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(520, 500))
        MainWindow.setMaximumSize(QtCore.QSize(520, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 220, 85, 26))
        self.pushButton.setObjectName("pushButton")
        self.label_length = QtWidgets.QLabel(self.centralwidget)
        self.label_length.setGeometry(QtCore.QRect(40, 20, 251, 20))
        self.label_length.setObjectName("label_length")
        self.comboBox_ground_type = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ground_type.setGeometry(QtCore.QRect(40, 170, 231, 22))
        self.comboBox_ground_type.setObjectName("comboBox_ground_type")
        self.comboBox_ground_type.addItem("")
        self.comboBox_ground_type.addItem("")
        self.comboBox_ground_type.addItem("")
        self.comboBox_ground_type.addItem("")
        self.comboBox_ground_type.addItem("")
        self.comboBox_ground_type.addItem("")
        self.comboBox_ground_type.addItem("")
        self.comboBox_ground_type.addItem("")
        self.label_length_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_length_2.setGeometry(QtCore.QRect(40, 140, 251, 20))
        self.label_length_2.setObjectName("label_length_2")
        self.doubleSpinBox_length = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_length.setGeometry(QtCore.QRect(330, 20, 62, 22))
        self.doubleSpinBox_length.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.doubleSpinBox_length.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_length.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_length.setDecimals(3)
        self.doubleSpinBox_length.setMaximum(1e+32)
        self.doubleSpinBox_length.setObjectName("doubleSpinBox_length")
        self.label_width = QtWidgets.QLabel(self.centralwidget)
        self.label_width.setGeometry(QtCore.QRect(40, 60, 251, 20))
        self.label_width.setObjectName("label_width")
        self.doubleSpinBox_width = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_width.setGeometry(QtCore.QRect(330, 60, 62, 22))
        self.doubleSpinBox_width.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.doubleSpinBox_width.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_width.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_width.setDecimals(3)
        self.doubleSpinBox_width.setMaximum(1e+32)
        self.doubleSpinBox_width.setObjectName("doubleSpinBox_width")
        self.doubleSpinBox_height = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_height.setGeometry(QtCore.QRect(330, 100, 62, 22))
        self.doubleSpinBox_height.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.doubleSpinBox_height.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_height.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_height.setDecimals(3)
        self.doubleSpinBox_height.setMaximum(1e+32)
        self.doubleSpinBox_height.setObjectName("doubleSpinBox_height")
        self.label_height = QtWidgets.QLabel(self.centralwidget)
        self.label_height.setGeometry(QtCore.QRect(40, 100, 251, 20))
        self.label_height.setObjectName("label_height")
        self.label_width_top = QtWidgets.QLabel(self.centralwidget)
        self.label_width_top.setGeometry(QtCore.QRect(40, 370, 251, 20))
        self.label_width_top.setObjectName("label_width_top")
        self.doubleSpinBox_width_top = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_width_top.setGeometry(QtCore.QRect(290, 370, 81, 22))
        self.doubleSpinBox_width_top.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.doubleSpinBox_width_top.setReadOnly(True)
        self.doubleSpinBox_width_top.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_width_top.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_width_top.setDecimals(3)
        self.doubleSpinBox_width_top.setMaximum(1e+32)
        self.doubleSpinBox_width_top.setObjectName("doubleSpinBox_width_top")
        self.doubleSpinBox_length_top = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_length_top.setGeometry(QtCore.QRect(290, 330, 81, 22))
        self.doubleSpinBox_length_top.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.doubleSpinBox_length_top.setReadOnly(True)
        self.doubleSpinBox_length_top.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_length_top.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_length_top.setDecimals(3)
        self.doubleSpinBox_length_top.setMaximum(1e+32)
        self.doubleSpinBox_length_top.setObjectName("doubleSpinBox_length_top")
        self.label_length_top = QtWidgets.QLabel(self.centralwidget)
        self.label_length_top.setGeometry(QtCore.QRect(40, 330, 251, 20))
        self.label_length_top.setObjectName("label_length_top")
        self.doubleSpinBox_V = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_V.setGeometry(QtCore.QRect(290, 410, 81, 22))
        self.doubleSpinBox_V.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.doubleSpinBox_V.setReadOnly(True)
        self.doubleSpinBox_V.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_V.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_V.setDecimals(3)
        self.doubleSpinBox_V.setMaximum(1e+32)
        self.doubleSpinBox_V.setObjectName("doubleSpinBox_V")
        self.label_V = QtWidgets.QLabel(self.centralwidget)
        self.label_V.setGeometry(QtCore.QRect(40, 410, 251, 20))
        self.label_V.setObjectName("label_V")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 260, 481, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.doubleSpinBox_m = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_m.setGeometry(QtCore.QRect(290, 290, 81, 22))
        self.doubleSpinBox_m.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.doubleSpinBox_m.setReadOnly(True)
        self.doubleSpinBox_m.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_m.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_m.setDecimals(2)
        self.doubleSpinBox_m.setMaximum(1e+32)
        self.doubleSpinBox_m.setObjectName("doubleSpinBox_m")
        self.label_m = QtWidgets.QLabel(self.centralwidget)
        self.label_m.setGeometry(QtCore.QRect(40, 290, 251, 20))
        self.label_m.setObjectName("label_m")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ВОРон: Расчет объёма котлована"))
        self.pushButton.setText(_translate("MainWindow", "Расчет"))
        self.label_length.setText(_translate("MainWindow", "Введите длину основания котлована, м: "))
        self.comboBox_ground_type.setCurrentText(_translate("MainWindow", "Насыпной неуплотненный"))
        self.comboBox_ground_type.setItemText(0, _translate("MainWindow", "Насыпной неуплотненный"))
        self.comboBox_ground_type.setItemText(1, _translate("MainWindow", "Песчаный и гравийный"))
        self.comboBox_ground_type.setItemText(2, _translate("MainWindow", "Супесь"))
        self.comboBox_ground_type.setItemText(3, _translate("MainWindow", "Суглинок"))
        self.comboBox_ground_type.setItemText(4, _translate("MainWindow", "Глина"))
        self.comboBox_ground_type.setItemText(5, _translate("MainWindow", "Лёссы и лёссовидные"))
        self.comboBox_ground_type.setItemText(6, _translate("MainWindow", "Морёные песчаные и супесчаные"))
        self.comboBox_ground_type.setItemText(7, _translate("MainWindow", "Морёные суглинистые"))
        self.label_length_2.setText(_translate("MainWindow", "Выберите тип грунта :"))
        self.label_width.setText(_translate("MainWindow", "Введите ширину основания котлована, м: "))
        self.label_height.setText(_translate("MainWindow", "Введите высоту котлована, м:"))
        self.label_width_top.setText(_translate("MainWindow", "Ширина верха котлована, м:"))
        self.label_length_top.setText(_translate("MainWindow", "Длина верха котлована, м:"))
        self.label_V.setText(_translate("MainWindow", "Объём котлована, м3:"))
        self.label_m.setText(_translate("MainWindow", "Коэффициент заложения откоса \"m\""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
